# Generated by Django 4.1.2 on 2022-10-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address1", models.CharField(max_length=200)),
                ("address2", models.CharField(max_length=200)),
                ("direction", models.TextField(verbose_name="directions to your home")),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tel1", models.CharField(max_length=15)),
                ("tel2", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "marital status",
                "verbose_name_plural": "marital statuses",
            },
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_number", models.CharField(max_length=10, unique=True)),
                ("date_issued", models.DateField()),
                ("place_of_issue", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "passport",
                "verbose_name_plural": "passports",
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "marital status",
                "verbose_name_plural": "marital statuses",
            },
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("children", models.IntegerField(default=0)),
                ("dependents", models.IntegerField(default=0)),
                (
                    "marital_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.maritalstatus",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.religion",
                    ),
                ),
            ],
            options={
                "verbose_name": "other",
                "verbose_name_plural": "others",
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(blank=True, max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("middle_name", models.CharField(max_length=200)),
                ("alias_name", models.TextField(blank=True)),
                (
                    "ht_ft",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="height in feet"
                    ),
                ),
                (
                    "ht_in",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="height in inches"
                    ),
                ),
                (
                    "wt_ks",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="height in kilos"
                    ),
                ),
                (
                    "wt_lbs",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="height in pounds"
                    ),
                ),
                ("marks", models.TextField(verbose_name="any distinguishing marks")),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                ("pob", models.CharField(max_length=50, unique=True)),
                ("nationality", models.CharField(max_length=50, unique=True)),
                (
                    "overstayed",
                    models.BooleanField(
                        default=False, verbose_name="have oyu overstayed in any country"
                    ),
                ),
                (
                    "convicted",
                    models.BooleanField(
                        default=False,
                        verbose_name="have you ever been convicted or charged in St Lucia or any other country?",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.address",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.contact",
                    ),
                ),
                (
                    "passport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.passport",
                    ),
                ),
            ],
            options={
                "verbose_name": "applicant",
                "verbose_name_plural": "applicants",
            },
        ),
    ]
