# Generated by Django 4.1.2 on 2022-10-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(blank=True, max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("middle_name", models.CharField(max_length=200)),
                ("alias_name", models.TextField(blank=True)),
                (
                    "ht_ft",
                    models.FloatField(
                        default=0,
                        help_text="add your height in feet",
                        verbose_name="height",
                    ),
                ),
                (
                    "ht_in",
                    models.FloatField(
                        default=0,
                        help_text="add your height in inches",
                        verbose_name="height",
                    ),
                ),
                ("wt_ks", models.FloatField(default=0, verbose_name="height in kilos")),
                (
                    "wt_lbs",
                    models.FloatField(default=0, verbose_name="height in pounds"),
                ),
                (
                    "marks",
                    models.TextField(
                        blank=True, verbose_name="any distinguishing marks"
                    ),
                ),
                ("dob", models.DateField(null=True, verbose_name="date of birth")),
                (
                    "overstayed",
                    models.BooleanField(
                        default=False,
                        help_text="<br>Please check box if, Yes",
                        verbose_name="have you overstayed in any country",
                    ),
                ),
                (
                    "convicted",
                    models.BooleanField(
                        default=False,
                        help_text="Please check box if, Yes",
                        verbose_name="have you ever been convicted or charged in St Lucia or any other country?",
                    ),
                ),
            ],
            options={
                "verbose_name": "applicant",
                "verbose_name_plural": "applicants",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tel1", models.CharField(max_length=15)),
                ("tel2", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "marital status",
                "verbose_name_plural": "marital statuses",
            },
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "nationality",
                "verbose_name_plural": "nationalities",
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "religion",
                "verbose_name_plural": "religions",
            },
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_number", models.CharField(max_length=10, unique=True)),
                ("date_issued", models.DateField()),
                ("place_of_issue", models.CharField(max_length=50)),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "passport",
                "verbose_name_plural": "passports",
            },
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("children", models.IntegerField(default=0)),
                ("dependents", models.IntegerField(default=0)),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.applicant",
                    ),
                ),
                (
                    "marital_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.maritalstatus",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.religion",
                    ),
                ),
            ],
            options={
                "verbose_name": "other",
                "verbose_name_plural": "others",
            },
        ),
        migrations.AddField(
            model_name="applicant",
            name="marital_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.maritalstatus",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="nationality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.nationality",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="pob",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.country",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="religion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.religion",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address1", models.CharField(max_length=200)),
                ("address2", models.CharField(max_length=200)),
                ("direction", models.TextField(verbose_name="directions to your home")),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
    ]
