# Generated by Django 4.1.2 on 2022-10-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_alter_address_applicant_alter_applicant_pob"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "district",
                "verbose_name_plural": "districts",
            },
        ),
    ]
