# Generated by Django 4.1.2 on 2022-10-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_alter_applicant_ht_ft_alter_applicant_ht_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="wt_ks",
            field=models.FloatField(default=0, verbose_name="height in kilos"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="wt_lbs",
            field=models.FloatField(default=0, verbose_name="height in pounds"),
        ),
    ]
