# Generated by Django 4.1.2 on 2022-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0003_alter_applicant_wt_ks_alter_applicant_wt_lbs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="dob",
            field=models.DateField(null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="nationality",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="pob",
            field=models.CharField(max_length=50, verbose_name="place of birth"),
        ),
    ]
