# Generated by Django 4.1.2 on 2022-10-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0003_district"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ("-pk",),
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="applicant",
            options={
                "ordering": ("last_name",),
                "verbose_name": "applicant",
                "verbose_name_plural": "applicants",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-pk",),
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ("name",),
                "verbose_name": "country",
                "verbose_name_plural": "countries",
            },
        ),
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ("name",),
                "verbose_name": "district",
                "verbose_name_plural": "districts",
            },
        ),
        migrations.AlterModelOptions(
            name="maritalstatus",
            options={
                "ordering": ("status",),
                "verbose_name": "marital status",
                "verbose_name_plural": "marital statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="nationality",
            options={
                "ordering": ("name",),
                "verbose_name": "nationality",
                "verbose_name_plural": "nationalities",
            },
        ),
        migrations.AlterModelOptions(
            name="other",
            options={
                "ordering": ("-pk",),
                "verbose_name": "other",
                "verbose_name_plural": "others",
            },
        ),
        migrations.AlterModelOptions(
            name="passport",
            options={
                "ordering": ("-pk",),
                "verbose_name": "passport",
                "verbose_name_plural": "passports",
            },
        ),
        migrations.AlterModelOptions(
            name="religion",
            options={
                "ordering": ("name",),
                "verbose_name": "religion",
                "verbose_name_plural": "religions",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="address3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.district",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address2",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
