# Generated by Django 4.1.2 on 2022-10-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0004_alter_applicant_dob_alter_applicant_nationality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="address",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="passport",
        ),
        migrations.AddField(
            model_name="address",
            name="applicant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.applicant",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="marital_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.maritalstatus",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="religion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.religion",
            ),
        ),
        migrations.AddField(
            model_name="other",
            name="applicant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.applicant",
            ),
        ),
        migrations.AddField(
            model_name="passport",
            name="applicant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applicants.applicant",
            ),
        ),
    ]
