# Generated by Django 4.1.2 on 2022-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicants",
            "0005_remove_applicant_address_remove_applicant_contact_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="religion",
            options={"verbose_name": "religion", "verbose_name_plural": "religions"},
        ),
        migrations.AlterField(
            model_name="applicant",
            name="convicted",
            field=models.BooleanField(
                default=False,
                help_text="Please check box if, Yes",
                verbose_name="have you ever been convicted or charged in St Lucia or any other country?",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="overstayed",
            field=models.BooleanField(
                default=False,
                help_text="<br>Please check box if, Yes",
                verbose_name="have you overstayed in any country",
            ),
        ),
    ]
